//
//  AuthenticationController.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "RequestAccessTokenRequest.h"

@interface AuthenticationController : BaseController

/**
* Completion block definition for asynchronous call to Request Access Token */
typedef void (^CompletedPostRequestAccessToken)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    body    Required parameter: Example: 
*/
- (void) createRequestAccessTokenAsyncWithBody:(RequestAccessTokenRequest*) body
                completionBlock:(CompletedPostRequestAccessToken) onCompleted;

@end