//
//  AutocompleteController.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface AutocompleteController : BaseController

/**
* Completion block definition for asynchronous call to Exercises */
typedef void (^CompletedGetExercises)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    exerciseQuery    Required parameter: Example: 
*/
- (void) getExercisesAsyncWithExerciseQuery:(NSString*) exerciseQuery
                completionBlock:(CompletedGetExercises) onCompleted;

/**
* Completion block definition for asynchronous call to Diseases */
typedef void (^CompletedGetDiseases)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    diseaseQuery    Required parameter: Example: 
*/
- (void) getDiseasesAsyncWithDiseaseQuery:(NSString*) diseaseQuery
                completionBlock:(CompletedGetDiseases) onCompleted;

/**
* Completion block definition for asynchronous call to Lab Tests */
typedef void (^CompletedGetLabTests)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    labTestQuery    Required parameter: Example: 
*/
- (void) getLabTestsAsyncWithLabTestQuery:(NSString*) labTestQuery
                completionBlock:(CompletedGetLabTests) onCompleted;

/**
* Completion block definition for asynchronous call to Food Items */
typedef void (^CompletedGetFoodItems)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    foodItemQuery    Required parameter: Example: 
*/
- (void) getFoodItemsAsyncWithFoodItemQuery:(NSString*) foodItemQuery
                completionBlock:(CompletedGetFoodItems) onCompleted;

/**
* Completion block definition for asynchronous call to Generics */
typedef void (^CompletedGetGenerics)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    genericQuery    Required parameter: Example: 
*/
- (void) getGenericsAsyncWithGenericQuery:(NSString*) genericQuery
                completionBlock:(CompletedGetGenerics) onCompleted;

/**
* Completion block definition for asynchronous call to Medicines */
typedef void (^CompletedGetMedicines)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    medicineQuery    Required parameter: Example: 
*/
- (void) getMedicinesAsyncWithMedicineQuery:(NSString*) medicineQuery
                completionBlock:(CompletedGetMedicines) onCompleted;

@end