//
//  ChatController.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface ChatController : BaseController

/**
* Completion block definition for asynchronous call to Excercises Chat */
typedef void (^CompletedGetExcercisesChat)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
*/
- (void) getExcercisesChatWithCompletionBlock:(CompletedGetExcercisesChat) onCompleted;

/**
* Completion block definition for asynchronous call to Food Items Chat */
typedef void (^CompletedGetFoodItemsChat)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
*/
- (void) getFoodItemsChatWithCompletionBlock:(CompletedGetFoodItemsChat) onCompleted;

/**
* Completion block definition for asynchronous call to Medicine Chat */
typedef void (^CompletedGetMedicineChat)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
*/
- (void) getMedicineChatWithCompletionBlock:(CompletedGetMedicineChat) onCompleted;

@end