//
//  DiseasesController.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface DiseasesController : BaseController

/**
* Completion block definition for asynchronous call to Disease */
typedef void (^CompletedGetDisease)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    diseaseId    Required parameter: Example: 
*/
- (void) getDiseaseAsyncWithDiseaseId:(NSString*) diseaseId
                completionBlock:(CompletedGetDisease) onCompleted;

/**
* Completion block definition for asynchronous call to All Diseases */
typedef void (^CompletedGetAllDiseases)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
*/
- (void) getAllDiseasesAsyncWithPage:(int) page
                size:(int) size
                completionBlock:(CompletedGetAllDiseases) onCompleted;

/**
* Completion block definition for asynchronous call to Search Diseases */
typedef void (^CompletedGetSearchDiseases)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    diseaseQuery    Required parameter: Example: 
*/
- (void) searchDiseasesAsyncWithDiseaseQuery:(NSString*) diseaseQuery
                completionBlock:(CompletedGetSearchDiseases) onCompleted;

@end