//
//  DrugInteractionsController.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface DrugInteractionsController : BaseController

/**
* Completion block definition for asynchronous call to Generics Interactions */
typedef void (^CompletedGetGenericsInteractions)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    genericId    Required parameter: Example: 
*/
- (void) getGenericsInteractionsAsyncWithGenericId:(NSString*) genericId
                completionBlock:(CompletedGetGenericsInteractions) onCompleted;

/**
* Completion block definition for asynchronous call to Medicine Interactions */
typedef void (^CompletedGetMedicineInteractions)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    medicineId    Required parameter: Example: 
*/
- (void) getMedicineInteractionsAsyncWithMedicineId:(NSString*) medicineId
                completionBlock:(CompletedGetMedicineInteractions) onCompleted;

@end