//
//  ExercisesController.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface ExercisesController : BaseController

/**
* Completion block definition for asynchronous call to Exercise */
typedef void (^CompletedGetExercise)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    exerciseId    Required parameter: Example: 
*/
- (void) getExerciseAsyncWithExerciseId:(NSString*) exerciseId
                completionBlock:(CompletedGetExercise) onCompleted;

/**
* Completion block definition for asynchronous call to All Exercises */
typedef void (^CompletedGetAllExercises)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
*/
- (void) getAllExercisesAsyncWithPage:(int) page
                size:(int) size
                completionBlock:(CompletedGetAllExercises) onCompleted;

/**
* Completion block definition for asynchronous call to Search Exercises */
typedef void (^CompletedGetSearchExercises)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    exerciseQuery    Required parameter: Example: 
*/
- (void) searchExercisesAsyncWithExerciseQuery:(NSString*) exerciseQuery
                completionBlock:(CompletedGetSearchExercises) onCompleted;

@end