//
//  FoodController.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface FoodController : BaseController

/**
* Completion block definition for asynchronous call to Search Food Restaurants */
typedef void (^CompletedGetSearchFoodRestaurants)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    foodRestaurantQuery    Required parameter: Example: 
*/
- (void) searchFoodRestaurantsAsyncWithFoodRestaurantQuery:(NSString*) foodRestaurantQuery
                completionBlock:(CompletedGetSearchFoodRestaurants) onCompleted;

/**
* Completion block definition for asynchronous call to All Food Brands */
typedef void (^CompletedGetAllFoodBrands)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
*/
- (void) getAllFoodBrandsAsyncWithPage:(int) page
                size:(int) size
                completionBlock:(CompletedGetAllFoodBrands) onCompleted;

/**
* Completion block definition for asynchronous call to Food Items by Restaurant */
typedef void (^CompletedGetFoodItemsByRestaurant)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
* @param    foodRestaurantId    Required parameter: Example: 
*/
- (void) getFoodItemsByRestaurantAsyncWithPage:(int) page
                size:(int) size
                foodRestaurantId:(NSString*) foodRestaurantId
                completionBlock:(CompletedGetFoodItemsByRestaurant) onCompleted;

/**
* Completion block definition for asynchronous call to Search Food Brands */
typedef void (^CompletedGetSearchFoodBrands)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    foodBrandQuery    Required parameter: Example: 
*/
- (void) searchFoodBrandsAsyncWithFoodBrandQuery:(NSString*) foodBrandQuery
                completionBlock:(CompletedGetSearchFoodBrands) onCompleted;

/**
* Completion block definition for asynchronous call to Food Item */
typedef void (^CompletedGetFoodItem)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    foodItemId    Required parameter: Example: 
*/
- (void) getFoodItemAsyncWithFoodItemId:(NSString*) foodItemId
                completionBlock:(CompletedGetFoodItem) onCompleted;

/**
* Completion block definition for asynchronous call to All Food Items */
typedef void (^CompletedGetAllFoodItems)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
*/
- (void) getAllFoodItemsAsyncWithPage:(int) page
                size:(int) size
                completionBlock:(CompletedGetAllFoodItems) onCompleted;

/**
* Completion block definition for asynchronous call to Search Food Items */
typedef void (^CompletedGetSearchFoodItems)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    foodItemQuery    Required parameter: Example: 
*/
- (void) searchFoodItemsAsyncWithFoodItemQuery:(NSString*) foodItemQuery
                completionBlock:(CompletedGetSearchFoodItems) onCompleted;

/**
* Completion block definition for asynchronous call to All Food Restaurants */
typedef void (^CompletedGetAllFoodRestaurants)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
*/
- (void) getAllFoodRestaurantsAsyncWithPage:(int) page
                size:(int) size
                completionBlock:(CompletedGetAllFoodRestaurants) onCompleted;

/**
* Completion block definition for asynchronous call to Food Items by Brand */
typedef void (^CompletedGetFoodItemsByBrand)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* TODO: Add Description
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
* @param    foodBrandId    Required parameter: Example: 
*/
- (void) getFoodItemsByBrandAsyncWithPage:(int) page
                size:(int) size
                foodBrandId:(NSString*) foodBrandId
                completionBlock:(CompletedGetFoodItemsByBrand) onCompleted;

@end