//
//  GenericsController.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface GenericsController : BaseController

/**
* Completion block definition for asynchronous call to Generic */
typedef void (^CompletedGetGeneric)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get a generic by id
* @param    genericId    Required parameter: Example: 
*/
- (void) getGenericAsyncWithGenericId:(NSString*) genericId
                completionBlock:(CompletedGetGeneric) onCompleted;

/**
* Completion block definition for asynchronous call to Medicines by Generic */
typedef void (^CompletedGetMedicinesByGeneric)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get medicines containing the generic
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
* @param    exclusive    Required parameter: Example: 
* @param    genericId    Required parameter: Example: 
*/
- (void) getMedicinesByGenericAsyncWithPage:(int) page
                size:(int) size
                exclusive:(BOOL) exclusive
                genericId:(NSString*) genericId
                completionBlock:(CompletedGetMedicinesByGeneric) onCompleted;

/**
* Completion block definition for asynchronous call to All Generics */
typedef void (^CompletedGetAllGenerics)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* All generics
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
*/
- (void) getAllGenericsAsyncWithPage:(int) page
                size:(int) size
                completionBlock:(CompletedGetAllGenerics) onCompleted;

/**
* Completion block definition for asynchronous call to Search Generics */
typedef void (^CompletedGetSearchGenerics)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Search a generic by name
* @param    genericQuery    Required parameter: Example: 
*/
- (void) searchGenericsAsyncWithGenericQuery:(NSString*) genericQuery
                completionBlock:(CompletedGetSearchGenerics) onCompleted;

@end