//
//  LabTestsController.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface LabTestsController : BaseController

/**
* Completion block definition for asynchronous call to Lab Test */
typedef void (^CompletedGetLabTest)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get labtest by id
* @param    labTestId    Required parameter: Example: 
*/
- (void) getLabTestAsyncWithLabTestId:(NSString*) labTestId
                completionBlock:(CompletedGetLabTest) onCompleted;

/**
* Completion block definition for asynchronous call to All Lab Tests */
typedef void (^CompletedGetAllLabTests)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* All Lab tests
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
*/
- (void) getAllLabTestsAsyncWithPage:(int) page
                size:(int) size
                completionBlock:(CompletedGetAllLabTests) onCompleted;

/**
* Completion block definition for asynchronous call to Search Lab Tests */
typedef void (^CompletedGetSearchLabTests)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Search a lab test by name
* @param    labTestQuery    Required parameter: Example: 
*/
- (void) searchLabTestsAsyncWithLabTestQuery:(NSString*) labTestQuery
                completionBlock:(CompletedGetSearchLabTests) onCompleted;

@end