//
//  MedicinesController.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface MedicinesController : BaseController

/**
* Completion block definition for asynchronous call to Manufacturer */
typedef void (^CompletedGetManufacturer)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get a manufacturer by its id
* @param    manufacturerId    Required parameter: Id of the manufacturer
*/
- (void) getManufacturerAsyncWithManufacturerId:(NSString*) manufacturerId
                completionBlock:(CompletedGetManufacturer) onCompleted;

/**
* Completion block definition for asynchronous call to Search Manufacturers */
typedef void (^CompletedGetSearchManufacturers)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Search a manufacturer by its name
* @param    manufacturerQuery    Required parameter: Example: 
*/
- (void) searchManufacturersAsyncWithManufacturerQuery:(NSString*) manufacturerQuery
                completionBlock:(CompletedGetSearchManufacturers) onCompleted;

/**
* Completion block definition for asynchronous call to Common Side Effects */
typedef void (^CompletedGetCommonSideEffects)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get common side effects of a medicine
* @param    medicineId    Required parameter: Example: 
*/
- (void) getCommonSideEffectsAsyncWithMedicineId:(NSString*) medicineId
                completionBlock:(CompletedGetCommonSideEffects) onCompleted;

/**
* Completion block definition for asynchronous call to Popular Usage */
typedef void (^CompletedGetPopularUsage)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get popular usages of a medicine
* @param    medicineId    Required parameter: Example: 
*/
- (void) getPopularUsageAsyncWithMedicineId:(NSString*) medicineId
                completionBlock:(CompletedGetPopularUsage) onCompleted;

/**
* Completion block definition for asynchronous call to Medicines by Manufacturer */
typedef void (^CompletedGetMedicinesByManufacturer)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get medicines by a manufacturer
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
* @param    manufacturerId    Required parameter: Example: 
*/
- (void) getMedicinesByManufacturerAsyncWithPage:(int) page
                size:(int) size
                manufacturerId:(NSString*) manufacturerId
                completionBlock:(CompletedGetMedicinesByManufacturer) onCompleted;

/**
* Completion block definition for asynchronous call to Similar Medicines */
typedef void (^CompletedGetSimilarMedicines)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get similar medicines
* @param    medicineId    Required parameter: Example: 
*/
- (void) getSimilarMedicinesAsyncWithMedicineId:(NSString*) medicineId
                completionBlock:(CompletedGetSimilarMedicines) onCompleted;

/**
* Completion block definition for asynchronous call to Medicine */
typedef void (^CompletedGetMedicine)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get a medicine
* @param    medicineId    Required parameter: Example: 
*/
- (void) getMedicineAsyncWithMedicineId:(NSString*) medicineId
                completionBlock:(CompletedGetMedicine) onCompleted;

/**
* Completion block definition for asynchronous call to All Medicines */
typedef void (^CompletedGetAllMedicines)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get all medicines
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
*/
- (void) getAllMedicinesAsyncWithPage:(int) page
                size:(int) size
                completionBlock:(CompletedGetAllMedicines) onCompleted;

/**
* Completion block definition for asynchronous call to Search Medicines */
typedef void (^CompletedGetSearchMedicines)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Search a medicine by name
* @param    medicineQuery    Required parameter: Example: 
*/
- (void) searchMedicinesAsyncWithMedicineQuery:(NSString*) medicineQuery
                completionBlock:(CompletedGetSearchMedicines) onCompleted;

/**
* Completion block definition for asynchronous call to All Manufacturers */
typedef void (^CompletedGetAllManufacturers)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get all manufacturers
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
*/
- (void) getAllManufacturersAsyncWithPage:(int) page
                size:(int) size
                completionBlock:(CompletedGetAllManufacturers) onCompleted;

/**
* Completion block definition for asynchronous call to Alternative Medicines */
typedef void (^CompletedGetAlternativeMedicines)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get substitutes of a medicine
* @param    page    Required parameter: Example: 
* @param    size    Required parameter: Example: 
* @param    medicineId    Required parameter: Example: 
*/
- (void) getAlternativeMedicinesAsyncWithPage:(int) page
                size:(int) size
                medicineId:(NSString*) medicineId
                completionBlock:(CompletedGetAlternativeMedicines) onCompleted;

@end