//
//  Configuration.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef HealthOS_Configuration_h
#define HealthOS_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

/** extern reference to the config variable Host */
extern NSString* Configuration_Host;

/** The OAuth 2.0 access token to be set before API calls */
/** extern reference to the config variable OAuthAccessToken */
extern NSString* Configuration_OAuthAccessToken;

#endif
