//
//  Configuration.m
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"http://{%@}/api/v1";

/** Replace the value of Host with an appropriate value */
NSString* Configuration_Host = @"TODO: Replace";

/** The OAuth 2.0 access token to be set before API calls */
/** Replace the value of OAuthAccessToken with an appropriate value */
NSString* Configuration_OAuthAccessToken = @"TODO: Replace";

