//
//  AllExercisesResponse18.m
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import "AllExercisesResponse18.h"

@implementation AllExercisesResponse18

/**
* TODO: Write general description for this method
*/
@synthesize name;

/**
* TODO: Write general description for this method
*/
@synthesize caloryCount;

/**
* TODO: Write general description for this method
*/
@synthesize mcategory;

/**
* TODO: Write general description for this method
*/
@synthesize cardioSubcategory;

/**
* TODO: Write general description for this method
*/
@synthesize primaryMuscleGroup;

/**
* TODO: Write general description for this method
*/
@synthesize exerciseId;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"name": @"name",
        @"calory_count": @"caloryCount",
        @"category": @"mcategory",
        @"cardio_subcategory": @"cardioSubcategory",
        @"primary_muscle_group": @"primaryMuscleGroup",
        @"exercise_id": @"exerciseId"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end