//
//  AllFoodRestaurantsResponse.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_ALLFOODRESTAURANTSRESPONSE
#define APIMATIC_ALLFOODRESTAURANTSRESPONSE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol AllFoodRestaurantsResponse
@end

@interface AllFoodRestaurantsResponse : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* restaurantName;

/**
* TODO: Write general description for this field
*/
@property NSString* foodRestaurantId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif