//
//  AllFoodRestaurantsResponse.m
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import "AllFoodRestaurantsResponse.h"

@implementation AllFoodRestaurantsResponse

/**
* TODO: Write general description for this method
*/
@synthesize restaurantName;

/**
* TODO: Write general description for this method
*/
@synthesize foodRestaurantId;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"restaurant_name": @"restaurantName",
        @"food_restaurant_id": @"foodRestaurantId"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end