//
//  AllGenericsResponse.m
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import "AllGenericsResponse.h"

@implementation AllGenericsResponse

/**
* TODO: Write general description for this method
*/
@synthesize name;

/**
* TODO: Write general description for this method
*/
@synthesize pregnancyCategory;

/**
* TODO: Write general description for this method
*/
@synthesize lactationCategory;

/**
* TODO: Write general description for this method
*/
@synthesize instructions;

/**
* TODO: Write general description for this method
*/
@synthesize faqs;

/**
* TODO: Write general description for this method
*/
@synthesize genricId;

/**
* TODO: Write general description for this method
*/
@synthesize sideEffects;

/**
* TODO: Write general description for this method
*/
@synthesize howItWorks;

/**
* TODO: Write general description for this method
*/
@synthesize therapeuticClass;

/**
* TODO: Write general description for this method
*/
@synthesize usedFor;

/**
* TODO: Write general description for this method
*/
@synthesize strength;

/**
* TODO: Write general description for this method
*/
@synthesize schedule;

/**
* TODO: Write general description for this method
*/
@synthesize alcoholInteractionDescription;

/**
* TODO: Write general description for this method
*/
@synthesize alcoholNteraction;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"name": @"name",
        @"pregnancy_category": @"pregnancyCategory",
        @"lactation_category": @"lactationCategory",
        @"instructions": @"instructions",
        @"faqs": @"faqs",
        @"genric_id": @"genricId",
        @"side_effects": @"sideEffects",
        @"how_it_works": @"howItWorks",
        @"therapeutic_class": @"therapeuticClass",
        @"used_for": @"usedFor",
        @"strength": @"strength",
        @"schedule": @"schedule",
        @"alcohol_interaction_description": @"alcoholInteractionDescription",
        @"alcohol_nteraction": @"alcoholNteraction"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end