//
//  AllGenericsResponse.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_ALLGENERICSRESPONSE
#define APIMATIC_ALLGENERICSRESPONSE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol AllGenericsResponse
@end

@interface AllGenericsResponse : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* name;

/**
* TODO: Write general description for this field
*/
@property NSString* pregnancyCategory;

/**
* TODO: Write general description for this field
*/
@property NSString* lactationCategory;

/**
* TODO: Write general description for this field
*/
@property NSString* instructions;

/**
* TODO: Write general description for this field
*/
@property NSString* faqs;

/**
* TODO: Write general description for this field
*/
@property int genricId;

/**
* TODO: Write general description for this field
*/
@property NSString* sideEffects;

/**
* TODO: Write general description for this field
*/
@property NSString* howItWorks;

/**
* TODO: Write general description for this field
*/
@property NSString* therapeuticClass;

/**
* TODO: Write general description for this field
*/
@property NSString* usedFor;

/**
* TODO: Write general description for this field
*/
@property NSString* strength;

/**
* TODO: Write general description for this field
*/
@property NSString* schedule;

/**
* TODO: Write general description for this field
*/
@property NSString* alcoholInteractionDescription;

/**
* TODO: Write general description for this field
*/
@property BOOL alcoholNteraction;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif