//
//  AllLabTestsResponse.m
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import "AllLabTestsResponse.h"

@implementation AllLabTestsResponse

/**
* TODO: Write general description for this method
*/
@synthesize labTestName;

/**
* TODO: Write general description for this method
*/
@synthesize alternateName;

/**
* TODO: Write general description for this method
*/
@synthesize labTestId;

/**
* TODO: Write general description for this method
*/
@synthesize labTestData;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"lab_test_name": @"labTestName",
        @"alternate_name": @"alternateName",
        @"lab_test_id": @"labTestId",
        @"lab_test_data": @"labTestData"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end