//
//  AllLabTestsResponse.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_ALLLABTESTSRESPONSE
#define APIMATIC_ALLLABTESTSRESPONSE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "LabTestData34.h"


//protocol defined for deserialization of JSON
@protocol AllLabTestsResponse
@end

@interface AllLabTestsResponse : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* labTestName;

/**
* TODO: Write general description for this field
*/
@property NSString* alternateName;

/**
* TODO: Write general description for this field
*/
@property NSString* labTestId;

/**
* TODO: Write general description for this field
*/
@property LabTestData34* labTestData;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif