//
//  DiseasesResponse.m
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import "DiseasesResponse.h"

@implementation DiseasesResponse

/**
* TODO: Write general description for this method
*/
@synthesize diseaseName;

/**
* TODO: Write general description for this method
*/
@synthesize diseaseCat;

/**
* TODO: Write general description for this method
*/
@synthesize diseaseInfo;

/**
* TODO: Write general description for this method
*/
@synthesize diseaseId;

/**
* TODO: Write general description for this method
*/
@synthesize searchScore;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"disease_name": @"diseaseName",
        @"disease_cat": @"diseaseCat",
        @"disease_info": @"diseaseInfo",
        @"disease_id": @"diseaseId",
        @"search_score": @"searchScore"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end