//
//  FoodItemsByRestaurantResponse.m
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import "FoodItemsByRestaurantResponse.h"

@implementation FoodItemsByRestaurantResponse

/**
* TODO: Write general description for this method
*/
@synthesize itemName;

/**
* TODO: Write general description for this method
*/
@synthesize calories;

/**
* TODO: Write general description for this method
*/
@synthesize servingQty;

/**
* TODO: Write general description for this method
*/
@synthesize servingUnit;

/**
* TODO: Write general description for this method
*/
@synthesize foodItemId;

/**
* TODO: Write general description for this method
*/
@synthesize foodBrandId;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"item_name": @"itemName",
        @"calories": @"calories",
        @"serving_qty": @"servingQty",
        @"serving_unit": @"servingUnit",
        @"food_item_id": @"foodItemId",
        @"food_brand_id": @"foodBrandId"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end