//
//  LabTestData34.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_LABTESTDATA34
#define APIMATIC_LABTESTDATA34

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol LabTestData34
@end

@interface LabTestData34 : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* orderingInformation;

/**
* TODO: Write general description for this field
*/
@property NSString* laboratory;

/**
* TODO: Write general description for this field
*/
@property NSString* testCode;

/**
* TODO: Write general description for this field
*/
@property NSString* specimenTypes;

/**
* TODO: Write general description for this field
*/
@property NSString* containerTypes;

/**
* TODO: Write general description for this field
*/
@property NSString* collectionInstructions;

/**
* TODO: Write general description for this field
*/
@property NSString* frequency;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif