//
//  LabTestData.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_LABTESTDATA
#define APIMATIC_LABTESTDATA

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol LabTestData
@end

@interface LabTestData : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* orderingInformation;

/**
* TODO: Write general description for this field
*/
@property NSString* alternateNames;

/**
* TODO: Write general description for this field
*/
@property NSString* laboratory;

/**
* TODO: Write general description for this field
*/
@property NSString* testCode;

/**
* TODO: Write general description for this field
*/
@property NSString* specimenTypes;

/**
* TODO: Write general description for this field
*/
@property NSString* containerTypes;

/**
* TODO: Write general description for this field
*/
@property NSString* minimumAdultVolume;

/**
* TODO: Write general description for this field
*/
@property NSString* frequency;

/**
* TODO: Write general description for this field
*/
@property NSString* externalLaboratory;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif