//
//  MedicinesResponse.m
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import "MedicinesResponse.h"

@implementation MedicinesResponse

/**
* TODO: Write general description for this method
*/
@synthesize name;

/**
* TODO: Write general description for this method
*/
@synthesize form;

/**
* TODO: Write general description for this method
*/
@synthesize standardUnits;

/**
* TODO: Write general description for this method
*/
@synthesize packageForm;

/**
* TODO: Write general description for this method
*/
@synthesize price;

/**
* TODO: Write general description for this method
*/
@synthesize size;

/**
* TODO: Write general description for this method
*/
@synthesize manufacturer;

/**
* TODO: Write general description for this method
*/
@synthesize constituents;

/**
* TODO: Write general description for this method
*/
@synthesize schedule;

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize medicineId;

/**
* TODO: Write general description for this method
*/
@synthesize searchScore;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"name": @"name",
        @"form": @"form",
        @"standardUnits": @"standardUnits",
        @"packageForm": @"packageForm",
        @"price": @"price",
        @"size": @"size",
        @"manufacturer": @"manufacturer",
        @"constituents": @"constituents",
        @"schedule": @"schedule",
        @"id": @"mid",
        @"medicine_id": @"medicineId",
        @"search_score": @"searchScore"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end