//
//  RequestAccessTokenRequest.m
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import "RequestAccessTokenRequest.h"

@implementation RequestAccessTokenRequest

/**
* TODO: Write general description for this method
*/
@synthesize grantType;

/**
* TODO: Write general description for this method
*/
@synthesize clientId;

/**
* TODO: Write general description for this method
*/
@synthesize clientSecret;

/**
* TODO: Write general description for this method
*/
@synthesize scope;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"grant_type": @"grantType",
        @"client_id": @"clientId",
        @"client_secret": @"clientSecret",
        @"scope": @"scope"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end