//
//  RequestAccessTokenRequest.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_REQUESTACCESSTOKENREQUEST
#define APIMATIC_REQUESTACCESSTOKENREQUEST

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol RequestAccessTokenRequest
@end

@interface RequestAccessTokenRequest : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* grantType;

/**
* TODO: Write general description for this field
*/
@property NSString* clientId;

/**
* TODO: Write general description for this field
*/
@property NSString* clientSecret;

/**
* TODO: Write general description for this field
*/
@property NSString* scope;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif