//
//  SearchFoodBrandsResponse.h
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_SEARCHFOODBRANDSRESPONSE
#define APIMATIC_SEARCHFOODBRANDSRESPONSE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol SearchFoodBrandsResponse
@end

@interface SearchFoodBrandsResponse : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* logo;

/**
* TODO: Write general description for this field
*/
@property NSString* name;

/**
* TODO: Write general description for this field
*/
@property NSString* foodBrandId;

/**
* TODO: Write general description for this field
*/
@property double searchScore;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif