//
//  SearchFoodRestaurantsResponse.m
//  HealthOS
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import "SearchFoodRestaurantsResponse.h"

@implementation SearchFoodRestaurantsResponse

/**
* TODO: Write general description for this method
*/
@synthesize logo;

/**
* TODO: Write general description for this method
*/
@synthesize name;

/**
* TODO: Write general description for this method
*/
@synthesize foodRestaurantId;

/**
* TODO: Write general description for this method
*/
@synthesize searchScore;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"logo": @"logo",
        @"name": @"name",
        @"food_restaurant_id": @"foodRestaurantId",
        @"search_score": @"searchScore"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end